### ISSUE TITLE
Invalid blobs generated

### ISSUE THREAD

**Issue by loansindi** [hypebeast/go-osc#45] opened 2020-11-25 18:25 UTC
I'm working on an application that sends blobs for controlling some other software, and ran into an issue in which this library generates invalid blobs. Sample code to recreate issue:

```
package main

import (
	"fmt"
	"github.com/hypebeast/go-osc/osc"
)

func main() {
	ip := "localhost"
	port := 7770
	client := osc.NewClient(ip, port)
	message := osc.NewMessage("/dmx/universe/0")
	b := make([]byte, 512)
	for i := 0; i < 512; i++ {
		b[i] = byte(i / 2)
	}
	message.Append(b)
	err := client.Send(message)
	fmt.Println(err)
	fmt.Println(message.Address)
	fmt.Println(message.Arguments)
}
```

OSCDump reports the following error:
liblo server error 9911 in path /dmx/universe/0: Invalid message received

If, however, I change the size of slice b to 511, everything works as intended:

```
package main

import (
	"fmt"
	"github.com/hypebeast/go-osc/osc"
)

func main() {
	ip := "localhost"
	port := 7770
	client := osc.NewClient(ip, port)
	message := osc.NewMessage("/dmx/universe/0")
	b := make([]byte, 511)
	for i := 0; i < 511; i++ {
		b[i] = byte(i / 2)
	}
	message.Append(b)
	err := client.Send(message)
	fmt.Println(err)
	fmt.Println(message.Address)
	fmt.Println(message.Arguments)
}
```
e3691c7e.717f8444 /dmx/universe/0 b [511 byte blob]

If there's any other useful information I can provide, let me know.

**Comment by peternewman** [comment] 2020-11-25 18:34
I was looking at the other end of this with @loansindi and at least part of the issue is this:
https://github.com/hypebeast/go-osc/blob/master/osc/osc.go#L998-L1002

It always returns a value of 4 regardless of the input, because you're basically doing:
`((4*(i/4))+(4*1))-i`
i.e.
`((i+4)-i)`
Which is always:
`4`

Switching to modulo ( https://golangbyexample.com/remainder-modulus-go-golang/ ) should fix it.

**Comment by hypebeast** [comment] 2021-03-18 22:57
Hi,

Thanks a lot for the PR and your issue. 

As far as I understand the padBytesNeeded (https://github.com/hypebeast/go-osc/blob/85fee7fed6921d46ac6261a794ddab814db86888/osc/osc.go#L1000) function doesn't always return 4. There are also tests for it

https://github.com/hypebeast/go-osc/blob/85fee7fed6921d46ac6261a794ddab814db86888/osc/osc_test.go#L351

But the function returns 4 if the length is a multiple of 4 and I guess this is not correct and should be 0 instead.

**Comment by peternewman** [comment] 2021-03-19 01:12
> Thanks a lot for the PR and your issue.

No worries.

> As far as I understand the padBytesNeeded (
> 
> https://github.com/hypebeast/go-osc/blob/85fee7fed6921d46ac6261a794ddab814db86888/osc/osc.go#L1000
> ) function doesn't always return 4. There are also tests for it
> 
> https://github.com/hypebeast/go-osc/blob/85fee7fed6921d46ac6261a794ddab814db86888/osc/osc_test.go#L351

Apologies, I hadn't spotted them. I think I've sort of worked out why Go is returning those crazy numbers (if you replace the second four with a 4.0, i.e. do it as a float, it always returns the value 4) but only in some casting circumstances I don't really understand:
https://play.golang.org/p/w7pcGdVPmc6

It doesn't seem to respect the modulo operator and negative sign as expected either, but the above does give the correct results (after a second negative).

> But the function returns 4 if the length is a multiple of 4 and I guess this is not correct and should be 0 instead.

Yes, I've added tests for both of those cases (and fixed the others) which appear to have broken some other bit of the code:
https://travis-ci.org/github/hypebeast/go-osc/jobs/763489113

Edit: now fixed too, although its still crashing for some reason I can't immediately spot.

**Comment by peternewman** [comment] 2021-03-19 02:17
I'm still a bit confused in the PR as you can probably tell. I don't know if there's something more fundamentally wrong in the code, or my attempts to fix it or the tests after fixing the calculation are wrong. Needs more pondering.

**Comment by chabad360** [comment] 2021-03-22 13:00
I'll try to test this later today, see where the issue lies.

Also, why are you doing `-(-i%4)` or even `-i%4` in the first place? It seems `i%4` is enough.

> https://play.golang.org/p/w7pcGdVPmc6

P.s. cleaned it up a little bit: https://play.golang.org/p/PJo6WTtzM5J

**Comment by peternewman** [comment] 2021-03-22 14:08
> I'll try to test this later today, see where the issue lies.

Thanks @chabad360 

> Also, why are you doing `-(-i%4)` or even `-i%4` in the first place?

The Internet suggested it as a clever/neat way to solve the issue, but looking here it's only going to work in some languages:
https://torstencurdt.com/tech/posts/modulo-of-negative-numbers/

> It seems `i%4` is enough.

It's not, and that's also the hint to what was going wrong with my existing code! i%4 gives the length of the excess bytes after a boundary, but we need the inverse of that, to find how many bytes of padding to add/remove.

| i | i%4 | 4-(i%4) | (4-(i%4))%4 |
| --- | --- | --- | --- |
| 0 | 0 | 4 | 0 |
| 1 | 1 | 3 | 3 |
| 2 | 2 | 2 | 2 |
| 3 | 3 | 1 | 1 |
| 4 | 4 | 4 | 0 |

https://play.golang.org/p/2echq3VIwVS

**Comment by chabad360** [comment] 2021-03-22 15:55
Just posted some comments on the PR.

**Closed** 2021-03-23 08:25 UTC

**Comment by peternewman** [comment] 2021-03-23 17:38
It's finally in @loansindi . Now I just need to do the bundle stuff our end too...
